### ISSUE TITLE
RBTMQ connection pool doesn't seem to be working

### ISSUE THREAD

**Issue by maximusunc** [ranking-agent/aragorn#136]
When I send the query below, some responses make it on to the queue, but many don't with this error:
```bash
2022-10-21 10:10:28,019 | INFO | aragorn_app:subservice_callback | 34037dc590d5: Receiving sub-service callback
Task exception was never retrieved
future: <Task finished name='Task-725' coro=<subservice_callback.<locals>.publish() done, defined at /Users/mwang/CoVar/translator/aragorn/aragorn/src/aragorn_app.py:142> exception=PoolInvalidStateError('acquire operation on closed pool')>
Traceback (most recent call last):
  File "/Users/mwang/CoVar/translator/aragorn/aragorn/src/aragorn_app.py", line 143, in publish
    async with channel_pool.acquire() as channel:
  File "/Users/mwang/.venv/aragorn/lib/python3.9/site-packages/aio_pika/pool.py", line 77, in acquire
    raise PoolInvalidStateError("acquire operation on closed pool")
aio_pika.pool.PoolInvalidStateError: acquire operation on closed pool
[2022-10-21 10:10:28,020: INFO/uvicorn.access]: 127.0.0.1:56964 - "POST /aragorn/callback/34037dc590d5 HTTP/1.1" 200
```

Query:
```bash
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": [
            "MONDO:0018956"
          ],
          "categories": [
            "biolink:Disease"
          ],
          "name": "Idiopathic bronchiectasis"
        },
        "n1": {
          "categories": [
            "biolink:ChemicalEntity"
          ]
        }
      },
      "edges": {
        "e0": {
          "subject": "n1",
          "object": "n0",
          "predicates": [
            "biolink:treats"
          ],
          "knowledge_type": "inferred"
        }
      }
    }
  },
  "log_level": "DEBUG"
}
```

This causes Aragorn to miss a bunch of responses, and then the original query has to wait an hour for those listening queues to time out.

**Comment by maximusunc** [comment]
Looks good!
